/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.71
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// A constraint violation present in the route optimization result.
    /// </summary>
    [DataContract(Name = "Violation")]
    public partial class RouteOptimizationViolation : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", EmitDefaultValue = true)]
        public RouteOptimizationViolationCode? Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationViolation" /> class.
        /// </summary>
        /// <param name="code">code.</param>
        /// <param name="constraint">JSONPath expression pointing to the constraint in the optimization request that is violated..</param>
        /// <param name="paths">JSONPath expressions pointing to the related entities in the optimization result that are involved in the violation..</param>
        public RouteOptimizationViolation(RouteOptimizationViolationCode? code = default(RouteOptimizationViolationCode?), string constraint = default(string), List<string> paths = default(List<string>))
        {
            this.Code = code;
            this.Constraint = constraint;
            this.Paths = paths;
        }

        /// <summary>
        /// JSONPath expression pointing to the constraint in the optimization request that is violated.
        /// </summary>
        /// <value>JSONPath expression pointing to the constraint in the optimization request that is violated.</value>
        [DataMember(Name = "constraint", EmitDefaultValue = true)]
        public string Constraint { get; set; }

        /// <summary>
        /// JSONPath expressions pointing to the related entities in the optimization result that are involved in the violation.
        /// </summary>
        /// <value>JSONPath expressions pointing to the related entities in the optimization result that are involved in the violation.</value>
        [DataMember(Name = "paths", EmitDefaultValue = false)]
        public List<string> Paths { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptimizationViolation {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Constraint: ").Append(Constraint).Append("\n");
            sb.Append("  Paths: ").Append(Paths).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
