/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.28
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// Describes the end of a route assigned to the vehicle.
    /// </summary>
    [DataContract(Name = "VehicleEnd")]
    public partial class RouteOptimizationVehicleEnd : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationVehicleEnd" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RouteOptimizationVehicleEnd() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationVehicleEnd" /> class.
        /// </summary>
        /// <param name="locationId">The unique identifier of the location where a route assigned to the vehicle must end. When omitted, the route ends at the location of the last stop..</param>
        /// <param name="latestEndTime">The latest point in time a route assigned to the vehicle may end. This must not be earlier than the vehicle&#39;s earliest start time. When used in conjunction with a latest start time, the latest end time must not be earlier than the latest start time. Formatted according to [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). The date must not be before &#x60;1970-01-01T00:00:00+00:00&#x60; nor after &#x60;2037-12-31T23:59:59+00:00&#x60;. The date must provide an offset to UTC. (required).</param>
        /// <param name="duration">Describes how long [s] it takes for the vehicle to wrap up at its end location before the route ends. (default to 0).</param>
        public RouteOptimizationVehicleEnd(string locationId = default(string), DateTimeOffset? latestEndTime = default(DateTimeOffset?), int? duration = 0)
        {
            // to ensure "latestEndTime" is required (not null)
            if (latestEndTime == null)
            {
                throw new ArgumentNullException("latestEndTime is a required property for RouteOptimizationVehicleEnd and cannot be null");
            }
            this.LatestEndTime = latestEndTime;
            this.LocationId = locationId;
            // use default value if no "duration" provided
            this.Duration = duration ?? 0;
        }

        /// <summary>
        /// The unique identifier of the location where a route assigned to the vehicle must end. When omitted, the route ends at the location of the last stop.
        /// </summary>
        /// <value>The unique identifier of the location where a route assigned to the vehicle must end. When omitted, the route ends at the location of the last stop.</value>
        /// <example>BRUSSELS</example>
        [DataMember(Name = "locationId", EmitDefaultValue = true)]
        public string LocationId { get; set; }

        /// <summary>
        /// The latest point in time a route assigned to the vehicle may end. This must not be earlier than the vehicle&#39;s earliest start time. When used in conjunction with a latest start time, the latest end time must not be earlier than the latest start time. Formatted according to [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). The date must not be before &#x60;1970-01-01T00:00:00+00:00&#x60; nor after &#x60;2037-12-31T23:59:59+00:00&#x60;. The date must provide an offset to UTC.
        /// </summary>
        /// <value>The latest point in time a route assigned to the vehicle may end. This must not be earlier than the vehicle&#39;s earliest start time. When used in conjunction with a latest start time, the latest end time must not be earlier than the latest start time. Formatted according to [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). The date must not be before &#x60;1970-01-01T00:00:00+00:00&#x60; nor after &#x60;2037-12-31T23:59:59+00:00&#x60;. The date must provide an offset to UTC.</value>
        /// <example>2023-10-03T16:00Z</example>
        [DataMember(Name = "latestEndTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset? LatestEndTime { get; set; }

        /// <summary>
        /// Describes how long [s] it takes for the vehicle to wrap up at its end location before the route ends.
        /// </summary>
        /// <value>Describes how long [s] it takes for the vehicle to wrap up at its end location before the route ends.</value>
        /// <example>1800</example>
        [DataMember(Name = "duration", EmitDefaultValue = true)]
        public int? Duration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptimizationVehicleEnd {\n");
            sb.Append("  LocationId: ").Append(LocationId).Append("\n");
            sb.Append("  LatestEndTime: ").Append(LatestEndTime).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LocationId (string) maxLength
            if (this.LocationId != null && this.LocationId.Length > 36)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LocationId, length must be less than 36.", new [] { "LocationId" });
            }

            // LocationId (string) minLength
            if (this.LocationId != null && this.LocationId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LocationId, length must be greater than 1.", new [] { "LocationId" });
            }

            if (this.LocationId != null) {
                // LocationId (string) pattern
                Regex regexLocationId = new Regex(@"^[a-zA-Z0-9_-]{1,36}$", RegexOptions.CultureInvariant);
                if (!regexLocationId.Match(this.LocationId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LocationId, must match a pattern of " + regexLocationId, new [] { "LocationId" });
                }
            }

            // Duration (int?) minimum
            if (this.Duration < (int?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Duration, must be a value greater than or equal to 0.", new [] { "Duration" });
            }

            yield break;
        }
    }

}
