/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.39
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// A constraint on the combination of orders and compartments belonging to a certain category.
    /// </summary>
    [DataContract(Name = "OrderCompartmentCombinationConstraint")]
    public partial class RouteOptimizationOrderCompartmentCombinationConstraint : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public RouteOptimizationOrderCompartmentCombinationConstraintType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationOrderCompartmentCombinationConstraint" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RouteOptimizationOrderCompartmentCombinationConstraint() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationOrderCompartmentCombinationConstraint" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="orderCategory">The category of orders to which the constraint applies. The constraint will be ignored when no order belongs to this category. (required).</param>
        /// <param name="compartmentCategory">The category of compartments to which the constraint applies. The constraint will be ignored when no compartment belongs to this category. (required).</param>
        public RouteOptimizationOrderCompartmentCombinationConstraint(RouteOptimizationOrderCompartmentCombinationConstraintType type = default(RouteOptimizationOrderCompartmentCombinationConstraintType), string orderCategory = default(string), string compartmentCategory = default(string))
        {
            this.Type = type;
            // to ensure "orderCategory" is required (not null)
            if (orderCategory == null)
            {
                throw new ArgumentNullException("orderCategory is a required property for RouteOptimizationOrderCompartmentCombinationConstraint and cannot be null");
            }
            this.OrderCategory = orderCategory;
            // to ensure "compartmentCategory" is required (not null)
            if (compartmentCategory == null)
            {
                throw new ArgumentNullException("compartmentCategory is a required property for RouteOptimizationOrderCompartmentCombinationConstraint and cannot be null");
            }
            this.CompartmentCategory = compartmentCategory;
        }

        /// <summary>
        /// The category of orders to which the constraint applies. The constraint will be ignored when no order belongs to this category.
        /// </summary>
        /// <value>The category of orders to which the constraint applies. The constraint will be ignored when no order belongs to this category.</value>
        /// <example>FROZEN</example>
        [DataMember(Name = "orderCategory", IsRequired = true, EmitDefaultValue = true)]
        public string OrderCategory { get; set; }

        /// <summary>
        /// The category of compartments to which the constraint applies. The constraint will be ignored when no compartment belongs to this category.
        /// </summary>
        /// <value>The category of compartments to which the constraint applies. The constraint will be ignored when no compartment belongs to this category.</value>
        /// <example>COOLING_COMPARTMENT</example>
        [DataMember(Name = "compartmentCategory", IsRequired = true, EmitDefaultValue = true)]
        public string CompartmentCategory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptimizationOrderCompartmentCombinationConstraint {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  OrderCategory: ").Append(OrderCategory).Append("\n");
            sb.Append("  CompartmentCategory: ").Append(CompartmentCategory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // OrderCategory (string) maxLength
            if (this.OrderCategory != null && this.OrderCategory.Length > 36)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for OrderCategory, length must be less than 36.", new [] { "OrderCategory" });
            }

            // OrderCategory (string) minLength
            if (this.OrderCategory != null && this.OrderCategory.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for OrderCategory, length must be greater than 1.", new [] { "OrderCategory" });
            }

            if (this.OrderCategory != null) {
                // OrderCategory (string) pattern
                Regex regexOrderCategory = new Regex(@"^[a-zA-Z0-9_-]{1,36}$", RegexOptions.CultureInvariant);
                if (!regexOrderCategory.Match(this.OrderCategory).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for OrderCategory, must match a pattern of " + regexOrderCategory, new [] { "OrderCategory" });
                }
            }

            // CompartmentCategory (string) maxLength
            if (this.CompartmentCategory != null && this.CompartmentCategory.Length > 36)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CompartmentCategory, length must be less than 36.", new [] { "CompartmentCategory" });
            }

            // CompartmentCategory (string) minLength
            if (this.CompartmentCategory != null && this.CompartmentCategory.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CompartmentCategory, length must be greater than 1.", new [] { "CompartmentCategory" });
            }

            if (this.CompartmentCategory != null) {
                // CompartmentCategory (string) pattern
                Regex regexCompartmentCategory = new Regex(@"^[a-zA-Z0-9_-]{1,36}$", RegexOptions.CultureInvariant);
                if (!regexCompartmentCategory.Match(this.CompartmentCategory).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CompartmentCategory, must match a pattern of " + regexCompartmentCategory, new [] { "CompartmentCategory" });
                }
            }

            yield break;
        }
    }

}
