/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.42
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// For an order this describes how much capacity for a certain dimension is needed in the vehicle. For a vehicle or a compartment, this describes its capacity for a certain dimension. For each dimension, the sum of the values of orders loaded into the vehicle or compartment must be lower than or equal to the value of the vehicle or compartment.
    /// </summary>
    [DataContract(Name = "Load")]
    public partial class RouteOptimizationLoad : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationLoad" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RouteOptimizationLoad() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationLoad" /> class.
        /// </summary>
        /// <param name="dimension">Indicates the specific dimension of the load, such as its volume, weight, or size. (required).</param>
        /// <param name="value">Represents the numeric value associated with the load&#39;s dimension. This value could be the actual measurement or quantity of the load. (required).</param>
        public RouteOptimizationLoad(string dimension = default(string), double? value = default(double?))
        {
            // to ensure "dimension" is required (not null)
            if (dimension == null)
            {
                throw new ArgumentNullException("dimension is a required property for RouteOptimizationLoad and cannot be null");
            }
            this.Dimension = dimension;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for RouteOptimizationLoad and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// Indicates the specific dimension of the load, such as its volume, weight, or size.
        /// </summary>
        /// <value>Indicates the specific dimension of the load, such as its volume, weight, or size.</value>
        /// <example>VOLUME</example>
        [DataMember(Name = "dimension", IsRequired = true, EmitDefaultValue = true)]
        public string Dimension { get; set; }

        /// <summary>
        /// Represents the numeric value associated with the load&#39;s dimension. This value could be the actual measurement or quantity of the load.
        /// </summary>
        /// <value>Represents the numeric value associated with the load&#39;s dimension. This value could be the actual measurement or quantity of the load.</value>
        /// <example>3.5</example>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public double? Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptimizationLoad {\n");
            sb.Append("  Dimension: ").Append(Dimension).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Dimension (string) maxLength
            if (this.Dimension != null && this.Dimension.Length > 36)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Dimension, length must be less than 36.", new [] { "Dimension" });
            }

            // Dimension (string) minLength
            if (this.Dimension != null && this.Dimension.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Dimension, length must be greater than 1.", new [] { "Dimension" });
            }

            if (this.Dimension != null) {
                // Dimension (string) pattern
                Regex regexDimension = new Regex(@"^[a-zA-Z0-9_-]{1,36}$", RegexOptions.CultureInvariant);
                if (!regexDimension.Match(this.Dimension).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Dimension, must match a pattern of " + regexDimension, new [] { "Dimension" });
                }
            }

            // Value (double?) maximum
            if (this.Value > (double?)1000000)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, must be a value less than or equal to 1000000.", new [] { "Value" });
            }

            // Value (double?) minimum
            if (this.Value < (double?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, must be a value greater than or equal to 0.", new [] { "Value" });
            }

            yield break;
        }
    }

}
