/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.69
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// Restricts the maximum distance a vehicle may travel on a single approach: the leg by which it reaches a stop, or the route&#39;s end location. The constraint applies to an approach whose start location matches the start location category and whose end location matches the end location category. Optionally filtered to vehicles matching a vehicle category.
    /// </summary>
    [DataContract(Name = "MaximumApproachDistanceLocationConstraint")]
    public partial class RouteOptimizationMaximumApproachDistanceLocationConstraint : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationMaximumApproachDistanceLocationConstraint" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RouteOptimizationMaximumApproachDistanceLocationConstraint() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationMaximumApproachDistanceLocationConstraint" /> class.
        /// </summary>
        /// <param name="startLocationCategory">The constraint applies only to approaches whose start location matches this category. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches locations that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches locations that **do not** have that category. The constraint will be ignored if no location belongs to this category. (required).</param>
        /// <param name="endLocationCategory">The constraint applies only to approaches whose end location matches this category. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches locations that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches locations that **do not** have that category. The constraint will be ignored if no location belongs to this category. (required).</param>
        /// <param name="value">The maximum distance [m] a vehicle may travel on a matching approach. (required).</param>
        /// <param name="vehicleCategory">The constraint applies only to vehicles that match this category. When omitted, the constraint applies to all vehicles. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches vehicles that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches vehicles that **do not** have that category. If no vehicle matches this condition, the constraint is ignored..</param>
        public RouteOptimizationMaximumApproachDistanceLocationConstraint(string startLocationCategory = default(string), string endLocationCategory = default(string), int? value = default(int?), string vehicleCategory = default(string))
        {
            // to ensure "startLocationCategory" is required (not null)
            if (startLocationCategory == null)
            {
                throw new ArgumentNullException("startLocationCategory is a required property for RouteOptimizationMaximumApproachDistanceLocationConstraint and cannot be null");
            }
            this.StartLocationCategory = startLocationCategory;
            // to ensure "endLocationCategory" is required (not null)
            if (endLocationCategory == null)
            {
                throw new ArgumentNullException("endLocationCategory is a required property for RouteOptimizationMaximumApproachDistanceLocationConstraint and cannot be null");
            }
            this.EndLocationCategory = endLocationCategory;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for RouteOptimizationMaximumApproachDistanceLocationConstraint and cannot be null");
            }
            this.Value = value;
            this.VehicleCategory = vehicleCategory;
        }

        /// <summary>
        /// The constraint applies only to approaches whose start location matches this category. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches locations that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches locations that **do not** have that category. The constraint will be ignored if no location belongs to this category.
        /// </summary>
        /// <value>The constraint applies only to approaches whose start location matches this category. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches locations that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches locations that **do not** have that category. The constraint will be ignored if no location belongs to this category.</value>
        /// <example>CUSTOMER</example>
        [DataMember(Name = "startLocationCategory", IsRequired = true, EmitDefaultValue = true)]
        public string StartLocationCategory { get; set; }

        /// <summary>
        /// The constraint applies only to approaches whose end location matches this category. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches locations that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches locations that **do not** have that category. The constraint will be ignored if no location belongs to this category.
        /// </summary>
        /// <value>The constraint applies only to approaches whose end location matches this category. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches locations that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches locations that **do not** have that category. The constraint will be ignored if no location belongs to this category.</value>
        /// <example>CUSTOMER</example>
        [DataMember(Name = "endLocationCategory", IsRequired = true, EmitDefaultValue = true)]
        public string EndLocationCategory { get; set; }

        /// <summary>
        /// The maximum distance [m] a vehicle may travel on a matching approach.
        /// </summary>
        /// <value>The maximum distance [m] a vehicle may travel on a matching approach.</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public int? Value { get; set; }

        /// <summary>
        /// The constraint applies only to vehicles that match this category. When omitted, the constraint applies to all vehicles. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches vehicles that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches vehicles that **do not** have that category. If no vehicle matches this condition, the constraint is ignored.
        /// </summary>
        /// <value>The constraint applies only to vehicles that match this category. When omitted, the constraint applies to all vehicles. If this field contains a plain category name (e.g. &#x60;CATEGORY_A&#x60;), it matches vehicles that have this category. If this field starts with &#x60;!&#x60; (e.g. &#x60;!CATEGORY_A&#x60;), it matches vehicles that **do not** have that category. If no vehicle matches this condition, the constraint is ignored.</value>
        /// <example>SMALL_TRUCK</example>
        [DataMember(Name = "vehicleCategory", EmitDefaultValue = true)]
        public string VehicleCategory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptimizationMaximumApproachDistanceLocationConstraint {\n");
            sb.Append("  StartLocationCategory: ").Append(StartLocationCategory).Append("\n");
            sb.Append("  EndLocationCategory: ").Append(EndLocationCategory).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  VehicleCategory: ").Append(VehicleCategory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // StartLocationCategory (string) maxLength
            if (this.StartLocationCategory != null && this.StartLocationCategory.Length > 201)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StartLocationCategory, length must be less than 201.", new [] { "StartLocationCategory" });
            }

            // StartLocationCategory (string) minLength
            if (this.StartLocationCategory != null && this.StartLocationCategory.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StartLocationCategory, length must be greater than 1.", new [] { "StartLocationCategory" });
            }

            if (this.StartLocationCategory != null) {
                // StartLocationCategory (string) pattern
                Regex regexStartLocationCategory = new Regex(@"^!?[a-zA-Z0-9_-]{1,200}$", RegexOptions.CultureInvariant);
                if (!regexStartLocationCategory.Match(this.StartLocationCategory).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StartLocationCategory, must match a pattern of " + regexStartLocationCategory, new [] { "StartLocationCategory" });
                }
            }

            // EndLocationCategory (string) maxLength
            if (this.EndLocationCategory != null && this.EndLocationCategory.Length > 201)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EndLocationCategory, length must be less than 201.", new [] { "EndLocationCategory" });
            }

            // EndLocationCategory (string) minLength
            if (this.EndLocationCategory != null && this.EndLocationCategory.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EndLocationCategory, length must be greater than 1.", new [] { "EndLocationCategory" });
            }

            if (this.EndLocationCategory != null) {
                // EndLocationCategory (string) pattern
                Regex regexEndLocationCategory = new Regex(@"^!?[a-zA-Z0-9_-]{1,200}$", RegexOptions.CultureInvariant);
                if (!regexEndLocationCategory.Match(this.EndLocationCategory).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EndLocationCategory, must match a pattern of " + regexEndLocationCategory, new [] { "EndLocationCategory" });
                }
            }

            // Value (int?) minimum
            if (this.Value < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, must be a value greater than or equal to 1.", new [] { "Value" });
            }

            // VehicleCategory (string) maxLength
            if (this.VehicleCategory != null && this.VehicleCategory.Length > 201)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VehicleCategory, length must be less than 201.", new [] { "VehicleCategory" });
            }

            // VehicleCategory (string) minLength
            if (this.VehicleCategory != null && this.VehicleCategory.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VehicleCategory, length must be greater than 1.", new [] { "VehicleCategory" });
            }

            if (this.VehicleCategory != null) {
                // VehicleCategory (string) pattern
                Regex regexVehicleCategory = new Regex(@"^!?[a-zA-Z0-9_-]{1,200}$", RegexOptions.CultureInvariant);
                if (!regexVehicleCategory.Match(this.VehicleCategory).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VehicleCategory, must match a pattern of " + regexVehicleCategory, new [] { "VehicleCategory" });
                }
            }

            yield break;
        }
    }

}
