/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.28
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// Defines an extra cost that is applied whenever an order is loaded onto the vehicle and the vehicle&#39;s load exceeds the specified threshold.
    /// </summary>
    [DataContract(Name = "OverloadCost")]
    public partial class RouteOptimizationOverloadCost : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationOverloadCost" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RouteOptimizationOverloadCost() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationOverloadCost" /> class.
        /// </summary>
        /// <param name="dimension">Indicates the dimension of the load, to which the threshold applies. (required).</param>
        /// <param name="threshold">The threshold for the specified load dimension.  When an order is loaded, only the part of that order which contributes to exceeding the threshold is considered for the extra cost. (required).</param>
        /// <param name="extraPerUnit">Specifies the extra cost per unit when loading an order which exceeds the threshold. (required).</param>
        public RouteOptimizationOverloadCost(string dimension = default(string), double? threshold = default(double?), double? extraPerUnit = default(double?))
        {
            // to ensure "dimension" is required (not null)
            if (dimension == null)
            {
                throw new ArgumentNullException("dimension is a required property for RouteOptimizationOverloadCost and cannot be null");
            }
            this.Dimension = dimension;
            // to ensure "threshold" is required (not null)
            if (threshold == null)
            {
                throw new ArgumentNullException("threshold is a required property for RouteOptimizationOverloadCost and cannot be null");
            }
            this.Threshold = threshold;
            // to ensure "extraPerUnit" is required (not null)
            if (extraPerUnit == null)
            {
                throw new ArgumentNullException("extraPerUnit is a required property for RouteOptimizationOverloadCost and cannot be null");
            }
            this.ExtraPerUnit = extraPerUnit;
        }

        /// <summary>
        /// Indicates the dimension of the load, to which the threshold applies.
        /// </summary>
        /// <value>Indicates the dimension of the load, to which the threshold applies.</value>
        /// <example>WEIGHT</example>
        [DataMember(Name = "dimension", IsRequired = true, EmitDefaultValue = true)]
        public string Dimension { get; set; }

        /// <summary>
        /// The threshold for the specified load dimension.  When an order is loaded, only the part of that order which contributes to exceeding the threshold is considered for the extra cost.
        /// </summary>
        /// <value>The threshold for the specified load dimension.  When an order is loaded, only the part of that order which contributes to exceeding the threshold is considered for the extra cost.</value>
        /// <example>40</example>
        [DataMember(Name = "threshold", IsRequired = true, EmitDefaultValue = true)]
        public double? Threshold { get; set; }

        /// <summary>
        /// Specifies the extra cost per unit when loading an order which exceeds the threshold.
        /// </summary>
        /// <value>Specifies the extra cost per unit when loading an order which exceeds the threshold.</value>
        [DataMember(Name = "extraPerUnit", IsRequired = true, EmitDefaultValue = true)]
        public double? ExtraPerUnit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptimizationOverloadCost {\n");
            sb.Append("  Dimension: ").Append(Dimension).Append("\n");
            sb.Append("  Threshold: ").Append(Threshold).Append("\n");
            sb.Append("  ExtraPerUnit: ").Append(ExtraPerUnit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Dimension (string) maxLength
            if (this.Dimension != null && this.Dimension.Length > 36)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Dimension, length must be less than 36.", new [] { "Dimension" });
            }

            // Dimension (string) minLength
            if (this.Dimension != null && this.Dimension.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Dimension, length must be greater than 1.", new [] { "Dimension" });
            }

            if (this.Dimension != null) {
                // Dimension (string) pattern
                Regex regexDimension = new Regex(@"^[a-zA-Z0-9_-]{1,36}$", RegexOptions.CultureInvariant);
                if (!regexDimension.Match(this.Dimension).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Dimension, must match a pattern of " + regexDimension, new [] { "Dimension" });
                }
            }

            // Threshold (double?) maximum
            if (this.Threshold > (double?)1000000)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Threshold, must be a value less than or equal to 1000000.", new [] { "Threshold" });
            }

            // Threshold (double?) minimum
            if (this.Threshold < (double?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Threshold, must be a value greater than or equal to 0.", new [] { "Threshold" });
            }

            // ExtraPerUnit (double?) minimum
            if (this.ExtraPerUnit < (double?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ExtraPerUnit, must be a value greater than or equal to 0.", new [] { "ExtraPerUnit" });
            }

            yield break;
        }
    }

}
