/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.61
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// Defines the costs for charging at a charging station.
    /// </summary>
    [DataContract(Name = "ChargingStationCosts")]
    public partial class RouteOptimizationChargingStationCosts : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationChargingStationCosts" /> class.
        /// </summary>
        /// <param name="perKilowattHour">Specifies the cost for every kilowatt-hour charged. (default to 0D).</param>
        public RouteOptimizationChargingStationCosts(double? perKilowattHour = 0D)
        {
            // use default value if no "perKilowattHour" provided
            this.PerKilowattHour = perKilowattHour ?? 0D;
        }

        /// <summary>
        /// Specifies the cost for every kilowatt-hour charged.
        /// </summary>
        /// <value>Specifies the cost for every kilowatt-hour charged.</value>
        [DataMember(Name = "perKilowattHour", EmitDefaultValue = true)]
        public double? PerKilowattHour { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptimizationChargingStationCosts {\n");
            sb.Append("  PerKilowattHour: ").Append(PerKilowattHour).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PerKilowattHour (double?) minimum
            if (this.PerKilowattHour < (double?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PerKilowattHour, must be a value greater than or equal to 0.", new [] { "PerKilowattHour" });
            }

            yield break;
        }
    }

}
