/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.48
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// Specifies the maximum loads that can be either picked up from or delivered to this depot.
    /// </summary>
    [DataContract(Name = "DepotMaximumLoads")]
    public partial class RouteOptimizationDepotMaximumLoads : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptimizationDepotMaximumLoads" /> class.
        /// </summary>
        /// <param name="inbound">Defines the maximum loads that can be delivered to this depot..</param>
        /// <param name="outbound">Defines the maximum loads that can be picked up at this depot..</param>
        public RouteOptimizationDepotMaximumLoads(List<RouteOptimizationLoad> inbound = default(List<RouteOptimizationLoad>), List<RouteOptimizationLoad> outbound = default(List<RouteOptimizationLoad>))
        {
            this.Inbound = inbound;
            this.Outbound = outbound;
        }

        /// <summary>
        /// Defines the maximum loads that can be delivered to this depot.
        /// </summary>
        /// <value>Defines the maximum loads that can be delivered to this depot.</value>
        [DataMember(Name = "inbound", EmitDefaultValue = false)]
        public List<RouteOptimizationLoad> Inbound { get; set; }

        /// <summary>
        /// Defines the maximum loads that can be picked up at this depot.
        /// </summary>
        /// <value>Defines the maximum loads that can be picked up at this depot.</value>
        [DataMember(Name = "outbound", EmitDefaultValue = false)]
        public List<RouteOptimizationLoad> Outbound { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptimizationDepotMaximumLoads {\n");
            sb.Append("  Inbound: ").Append(Inbound).Append("\n");
            sb.Append("  Outbound: ").Append(Outbound).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
