/*
 * Route Optimization OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.39
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.optiflow.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.optiflow.Model
{
    /// <summary>
    /// Defines the constraint that applies to a task group. * &#x60;CONSECUTIVE&#x60; - Those tasks belonging to the task group that are scheduled on the same route must be scheduled consecutively. * &#x60;SAME_ROUTE&#x60; - All tasks belonging to the task group must be scheduled on the same route.
    /// </summary>
    /// <value>Defines the constraint that applies to a task group. * &#x60;CONSECUTIVE&#x60; - Those tasks belonging to the task group that are scheduled on the same route must be scheduled consecutively. * &#x60;SAME_ROUTE&#x60; - All tasks belonging to the task group must be scheduled on the same route.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RouteOptimizationTaskGroupConstraint
    {
        /// <summary>
        /// Enum CONSECUTIVE for value: CONSECUTIVE
        /// </summary>
        [EnumMember(Value = "CONSECUTIVE")]
        CONSECUTIVE = 1,

        /// <summary>
        /// Enum SAME_ROUTE for value: SAME_ROUTE
        /// </summary>
        [EnumMember(Value = "SAME_ROUTE")]
        SAME_ROUTE = 2
    }

}
