/*
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routeoptimization.optiflow.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.routeoptimization.optiflow.model.RouteOptimizationLoad;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Specifies the maximum loads that can be either picked up from or delivered to this depot.
 */
@JsonPropertyOrder({
  RouteOptimizationDepotMaximumLoads.JSON_PROPERTY_INBOUND,
  RouteOptimizationDepotMaximumLoads.JSON_PROPERTY_OUTBOUND
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-17T16:26:41.380842659Z[Etc/UTC]", comments = "Generator version: 7.5.0")
public class RouteOptimizationDepotMaximumLoads {
  public static final String JSON_PROPERTY_INBOUND = "inbound";
  private List<RouteOptimizationLoad> inbound = new ArrayList<>();

  public static final String JSON_PROPERTY_OUTBOUND = "outbound";
  private List<RouteOptimizationLoad> outbound = new ArrayList<>();

  public RouteOptimizationDepotMaximumLoads() { 
  }

  public RouteOptimizationDepotMaximumLoads inbound(List<RouteOptimizationLoad> inbound) {
    this.inbound = inbound;
    return this;
  }

  public RouteOptimizationDepotMaximumLoads addInboundItem(RouteOptimizationLoad inboundItem) {
    if (this.inbound == null) {
      this.inbound = new ArrayList<>();
    }
    this.inbound.add(inboundItem);
    return this;
  }

   /**
   * Defines the maximum loads that can be delivered to this depot.
   * @return inbound
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INBOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RouteOptimizationLoad> getInbound() {
    return inbound;
  }


  @JsonProperty(JSON_PROPERTY_INBOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInbound(List<RouteOptimizationLoad> inbound) {
    this.inbound = inbound;
  }


  public RouteOptimizationDepotMaximumLoads outbound(List<RouteOptimizationLoad> outbound) {
    this.outbound = outbound;
    return this;
  }

  public RouteOptimizationDepotMaximumLoads addOutboundItem(RouteOptimizationLoad outboundItem) {
    if (this.outbound == null) {
      this.outbound = new ArrayList<>();
    }
    this.outbound.add(outboundItem);
    return this;
  }

   /**
   * Defines the maximum loads that can be picked up at this depot.
   * @return outbound
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTBOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RouteOptimizationLoad> getOutbound() {
    return outbound;
  }


  @JsonProperty(JSON_PROPERTY_OUTBOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutbound(List<RouteOptimizationLoad> outbound) {
    this.outbound = outbound;
  }


  /**
   * Return true if this DepotMaximumLoads object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteOptimizationDepotMaximumLoads depotMaximumLoads = (RouteOptimizationDepotMaximumLoads) o;
    return Objects.equals(this.inbound, depotMaximumLoads.inbound) &&
        Objects.equals(this.outbound, depotMaximumLoads.outbound);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inbound, outbound);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteOptimizationDepotMaximumLoads {\n");
    sb.append("    inbound: ").append(toIndentedString(inbound)).append("\n");
    sb.append("    outbound: ").append(toIndentedString(outbound)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `inbound` to the URL query string
    if (getInbound() != null) {
      for (int i = 0; i < getInbound().size(); i++) {
        if (getInbound().get(i) != null) {
          joiner.add(getInbound().get(i).toUrlQueryString(String.format("%sinbound%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `outbound` to the URL query string
    if (getOutbound() != null) {
      for (int i = 0; i < getOutbound().size(); i++) {
        if (getOutbound().get(i) != null) {
          joiner.add(getOutbound().get(i).toUrlQueryString(String.format("%soutbound%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

