/*
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.39
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routeoptimization.optiflow.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.routeoptimization.optiflow.model.RouteOptimizationChargingStation;
import com.ptvgroup.developer.client.routeoptimization.optiflow.model.RouteOptimizationLayoverCondition;
import com.ptvgroup.developer.client.routeoptimization.optiflow.model.RouteOptimizationStopProperties;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * A specific location where goods have to be picked up or delivered, layovers can be scheduled, or vehicles are located.
 */
@JsonPropertyOrder({
  RouteOptimizationLocation.JSON_PROPERTY_ID,
  RouteOptimizationLocation.JSON_PROPERTY_LATITUDE,
  RouteOptimizationLocation.JSON_PROPERTY_LONGITUDE,
  RouteOptimizationLocation.JSON_PROPERTY_MATCH_SIDE_OF_STREET,
  RouteOptimizationLocation.JSON_PROPERTY_STOP_PROPERTIES,
  RouteOptimizationLocation.JSON_PROPERTY_CHARGING_STATIONS,
  RouteOptimizationLocation.JSON_PROPERTY_LAYOVER,
  RouteOptimizationLocation.JSON_PROPERTY_CATEGORIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-19T11:48:12.214027216Z[Etc/UTC]", comments = "Generator version: 7.5.0")
public class RouteOptimizationLocation {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_LATITUDE = "latitude";
  private Double latitude;

  public static final String JSON_PROPERTY_LONGITUDE = "longitude";
  private Double longitude;

  public static final String JSON_PROPERTY_MATCH_SIDE_OF_STREET = "matchSideOfStreet";
  private Boolean matchSideOfStreet = false;

  public static final String JSON_PROPERTY_STOP_PROPERTIES = "stopProperties";
  private RouteOptimizationStopProperties stopProperties;

  public static final String JSON_PROPERTY_CHARGING_STATIONS = "chargingStations";
  private List<RouteOptimizationChargingStation> chargingStations;

  public static final String JSON_PROPERTY_LAYOVER = "layover";
  private RouteOptimizationLayoverCondition layover = RouteOptimizationLayoverCondition.DISALLOW;

  public static final String JSON_PROPERTY_CATEGORIES = "categories";
  private List<String> categories = new ArrayList<>();

  public RouteOptimizationLocation() { 
  }

  public RouteOptimizationLocation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique identifier of the location.
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public RouteOptimizationLocation latitude(Double latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * The latitude value of the location in degrees (WGS84/EPSG:4326) from south to north.
   * minimum: -90
   * maximum: 90
   * @return latitude
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getLatitude() {
    return latitude;
  }


  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }


  public RouteOptimizationLocation longitude(Double longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * The longitude value of the location in degrees (WGS84/EPSG:4326) from west to east.
   * minimum: -180
   * maximum: 180
   * @return longitude
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getLongitude() {
    return longitude;
  }


  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }


  public RouteOptimizationLocation matchSideOfStreet(Boolean matchSideOfStreet) {
    this.matchSideOfStreet = matchSideOfStreet;
    return this;
  }

   /**
   * Requires the vehicle to approach from the side of the street where the location is situated. This prevents the driver from needing to cross the street.
   * @return matchSideOfStreet
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_SIDE_OF_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMatchSideOfStreet() {
    return matchSideOfStreet;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_SIDE_OF_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchSideOfStreet(Boolean matchSideOfStreet) {
    this.matchSideOfStreet = matchSideOfStreet;
  }


  public RouteOptimizationLocation stopProperties(RouteOptimizationStopProperties stopProperties) {
    this.stopProperties = stopProperties;
    return this;
  }

   /**
   * Get stopProperties
   * @return stopProperties
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STOP_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RouteOptimizationStopProperties getStopProperties() {
    return stopProperties;
  }


  @JsonProperty(JSON_PROPERTY_STOP_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStopProperties(RouteOptimizationStopProperties stopProperties) {
    this.stopProperties = stopProperties;
  }


  public RouteOptimizationLocation chargingStations(List<RouteOptimizationChargingStation> chargingStations) {
    this.chargingStations = chargingStations;
    return this;
  }

  public RouteOptimizationLocation addChargingStationsItem(RouteOptimizationChargingStation chargingStationsItem) {
    if (this.chargingStations == null) {
      this.chargingStations = new ArrayList<>();
    }
    this.chargingStations.add(chargingStationsItem);
    return this;
  }

   /**
   * Specifies the charging capabilities that can be used at the location for electric vehicles.
   * @return chargingStations
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGING_STATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RouteOptimizationChargingStation> getChargingStations() {
    return chargingStations;
  }


  @JsonProperty(JSON_PROPERTY_CHARGING_STATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargingStations(List<RouteOptimizationChargingStation> chargingStations) {
    this.chargingStations = chargingStations;
  }


  public RouteOptimizationLocation layover(RouteOptimizationLayoverCondition layover) {
    this.layover = layover;
    return this;
  }

   /**
   * Get layover
   * @return layover
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAYOVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RouteOptimizationLayoverCondition getLayover() {
    return layover;
  }


  @JsonProperty(JSON_PROPERTY_LAYOVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLayover(RouteOptimizationLayoverCondition layover) {
    this.layover = layover;
  }


  public RouteOptimizationLocation categories(List<String> categories) {
    this.categories = categories;
    return this;
  }

  public RouteOptimizationLocation addCategoriesItem(String categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * A list of categories the location belongs to that can be used to describe constraints or rules.
   * @return categories
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getCategories() {
    return categories;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategories(List<String> categories) {
    this.categories = categories;
  }


  /**
   * Return true if this Location object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteOptimizationLocation location = (RouteOptimizationLocation) o;
    return Objects.equals(this.id, location.id) &&
        Objects.equals(this.latitude, location.latitude) &&
        Objects.equals(this.longitude, location.longitude) &&
        Objects.equals(this.matchSideOfStreet, location.matchSideOfStreet) &&
        Objects.equals(this.stopProperties, location.stopProperties) &&
        Objects.equals(this.chargingStations, location.chargingStations) &&
        Objects.equals(this.layover, location.layover) &&
        Objects.equals(this.categories, location.categories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, latitude, longitude, matchSideOfStreet, stopProperties, chargingStations, layover, categories);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteOptimizationLocation {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    matchSideOfStreet: ").append(toIndentedString(matchSideOfStreet)).append("\n");
    sb.append("    stopProperties: ").append(toIndentedString(stopProperties)).append("\n");
    sb.append("    chargingStations: ").append(toIndentedString(chargingStations)).append("\n");
    sb.append("    layover: ").append(toIndentedString(layover)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `latitude` to the URL query string
    if (getLatitude() != null) {
      joiner.add(String.format("%slatitude%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLatitude()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `longitude` to the URL query string
    if (getLongitude() != null) {
      joiner.add(String.format("%slongitude%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLongitude()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `matchSideOfStreet` to the URL query string
    if (getMatchSideOfStreet() != null) {
      joiner.add(String.format("%smatchSideOfStreet%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMatchSideOfStreet()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `stopProperties` to the URL query string
    if (getStopProperties() != null) {
      joiner.add(getStopProperties().toUrlQueryString(prefix + "stopProperties" + suffix));
    }

    // add `chargingStations` to the URL query string
    if (getChargingStations() != null) {
      for (int i = 0; i < getChargingStations().size(); i++) {
        if (getChargingStations().get(i) != null) {
          joiner.add(getChargingStations().get(i).toUrlQueryString(String.format("%schargingStations%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `layover` to the URL query string
    if (getLayover() != null) {
      joiner.add(String.format("%slayover%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLayover()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `categories` to the URL query string
    if (getCategories() != null) {
      for (int i = 0; i < getCategories().size(); i++) {
        joiner.add(String.format("%scategories%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(getCategories().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    return joiner.toString();
  }
}

