/*
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.39
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routeoptimization.optiflow.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Metrics providing insights into the costs of a route.
 */
@JsonPropertyOrder({
  RouteOptimizationRouteCosts.JSON_PROPERTY_TOTAL,
  RouteOptimizationRouteCosts.JSON_PROPERTY_FIXED,
  RouteOptimizationRouteCosts.JSON_PROPERTY_TIME,
  RouteOptimizationRouteCosts.JSON_PROPERTY_DISTANCE,
  RouteOptimizationRouteCosts.JSON_PROPERTY_STOP,
  RouteOptimizationRouteCosts.JSON_PROPERTY_APPOINTMENT,
  RouteOptimizationRouteCosts.JSON_PROPERTY_LOAD,
  RouteOptimizationRouteCosts.JSON_PROPERTY_REPOSITIONING,
  RouteOptimizationRouteCosts.JSON_PROPERTY_ORDER_VEHICLE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-19T11:48:12.214027216Z[Etc/UTC]", comments = "Generator version: 7.5.0")
public class RouteOptimizationRouteCosts {
  public static final String JSON_PROPERTY_TOTAL = "total";
  private Double total;

  public static final String JSON_PROPERTY_FIXED = "fixed";
  private Double fixed;

  public static final String JSON_PROPERTY_TIME = "time";
  private Double time;

  public static final String JSON_PROPERTY_DISTANCE = "distance";
  private Double distance;

  public static final String JSON_PROPERTY_STOP = "stop";
  private Double stop;

  public static final String JSON_PROPERTY_APPOINTMENT = "appointment";
  private Double appointment;

  public static final String JSON_PROPERTY_LOAD = "load";
  private Double load;

  public static final String JSON_PROPERTY_REPOSITIONING = "repositioning";
  private Double repositioning;

  public static final String JSON_PROPERTY_ORDER_VEHICLE = "orderVehicle";
  private Double orderVehicle;

  public RouteOptimizationRouteCosts() { 
  }

  public RouteOptimizationRouteCosts total(Double total) {
    this.total = total;
    return this;
  }

   /**
   * The total cost of the route.
   * minimum: 0
   * maximum: 1000000
   * @return total
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(Double total) {
    this.total = total;
  }


  public RouteOptimizationRouteCosts fixed(Double fixed) {
    this.fixed = fixed;
    return this;
  }

   /**
   * The fixed cost of a the route.
   * minimum: 0
   * maximum: 1000000
   * @return fixed
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIXED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getFixed() {
    return fixed;
  }


  @JsonProperty(JSON_PROPERTY_FIXED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFixed(Double fixed) {
    this.fixed = fixed;
  }


  public RouteOptimizationRouteCosts time(Double time) {
    this.time = time;
    return this;
  }

   /**
   * The time cost of a the route. This includes the cost per hour as well as overtime costs.
   * minimum: 0
   * maximum: 1000000
   * @return time
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(Double time) {
    this.time = time;
  }


  public RouteOptimizationRouteCosts distance(Double distance) {
    this.distance = distance;
    return this;
  }

   /**
   * The distance cost of a the route. This includes the cost per kilometer as well as overdistance costs.
   * minimum: 0
   * maximum: 1000000
   * @return distance
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getDistance() {
    return distance;
  }


  @JsonProperty(JSON_PROPERTY_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDistance(Double distance) {
    this.distance = distance;
  }


  public RouteOptimizationRouteCosts stop(Double stop) {
    this.stop = stop;
    return this;
  }

   /**
   * The stop cost of a the route. This includes the cost per stop as well as overstops costs.
   * minimum: 0
   * maximum: 1000000
   * @return stop
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STOP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getStop() {
    return stop;
  }


  @JsonProperty(JSON_PROPERTY_STOP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStop(Double stop) {
    this.stop = stop;
  }


  public RouteOptimizationRouteCosts appointment(Double appointment) {
    this.appointment = appointment;
    return this;
  }

   /**
   * The appointment cost of a the route. Defined as the sum of all used time slots their cost per appointment.
   * minimum: 0
   * maximum: 1000000
   * @return appointment
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPOINTMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getAppointment() {
    return appointment;
  }


  @JsonProperty(JSON_PROPERTY_APPOINTMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppointment(Double appointment) {
    this.appointment = appointment;
  }


  public RouteOptimizationRouteCosts load(Double load) {
    this.load = load;
    return this;
  }

   /**
   * The load cost of the route, defined by overload costs.
   * minimum: 0
   * maximum: 1000000
   * @return load
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getLoad() {
    return load;
  }


  @JsonProperty(JSON_PROPERTY_LOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoad(Double load) {
    this.load = load;
  }


  public RouteOptimizationRouteCosts repositioning(Double repositioning) {
    this.repositioning = repositioning;
    return this;
  }

   /**
   * The reposition effort cost of the route.
   * minimum: 0
   * maximum: 1000000
   * @return repositioning
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REPOSITIONING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getRepositioning() {
    return repositioning;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITIONING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRepositioning(Double repositioning) {
    this.repositioning = repositioning;
  }


  public RouteOptimizationRouteCosts orderVehicle(Double orderVehicle) {
    this.orderVehicle = orderVehicle;
    return this;
  }

   /**
   * The order-vehicle violation cost of the route.  Defined as the sum of all violation costs for order-vehicle combination constraints applicable to the route.
   * minimum: 0
   * maximum: 1000000
   * @return orderVehicle
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORDER_VEHICLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getOrderVehicle() {
    return orderVehicle;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_VEHICLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderVehicle(Double orderVehicle) {
    this.orderVehicle = orderVehicle;
  }


  /**
   * Return true if this RouteCosts object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteOptimizationRouteCosts routeCosts = (RouteOptimizationRouteCosts) o;
    return Objects.equals(this.total, routeCosts.total) &&
        Objects.equals(this.fixed, routeCosts.fixed) &&
        Objects.equals(this.time, routeCosts.time) &&
        Objects.equals(this.distance, routeCosts.distance) &&
        Objects.equals(this.stop, routeCosts.stop) &&
        Objects.equals(this.appointment, routeCosts.appointment) &&
        Objects.equals(this.load, routeCosts.load) &&
        Objects.equals(this.repositioning, routeCosts.repositioning) &&
        Objects.equals(this.orderVehicle, routeCosts.orderVehicle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, fixed, time, distance, stop, appointment, load, repositioning, orderVehicle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteOptimizationRouteCosts {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    fixed: ").append(toIndentedString(fixed)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    stop: ").append(toIndentedString(stop)).append("\n");
    sb.append("    appointment: ").append(toIndentedString(appointment)).append("\n");
    sb.append("    load: ").append(toIndentedString(load)).append("\n");
    sb.append("    repositioning: ").append(toIndentedString(repositioning)).append("\n");
    sb.append("    orderVehicle: ").append(toIndentedString(orderVehicle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format("%stotal%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTotal()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `fixed` to the URL query string
    if (getFixed() != null) {
      joiner.add(String.format("%sfixed%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFixed()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `time` to the URL query string
    if (getTime() != null) {
      joiner.add(String.format("%stime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTime()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `distance` to the URL query string
    if (getDistance() != null) {
      joiner.add(String.format("%sdistance%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDistance()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `stop` to the URL query string
    if (getStop() != null) {
      joiner.add(String.format("%sstop%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStop()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `appointment` to the URL query string
    if (getAppointment() != null) {
      joiner.add(String.format("%sappointment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAppointment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `load` to the URL query string
    if (getLoad() != null) {
      joiner.add(String.format("%sload%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLoad()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `repositioning` to the URL query string
    if (getRepositioning() != null) {
      joiner.add(String.format("%srepositioning%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRepositioning()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `orderVehicle` to the URL query string
    if (getOrderVehicle() != null) {
      joiner.add(String.format("%sorderVehicle%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getOrderVehicle()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

