/*
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.39
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routeoptimization.optiflow.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Specifies an extra fixed cost and an increased cost per hour if the route duration exceeds a threshold. Either the fixed cost or the extra cost per hour must not be zero.
 */
@JsonPropertyOrder({
  RouteOptimizationOvertimeCost.JSON_PROPERTY_THRESHOLD,
  RouteOptimizationOvertimeCost.JSON_PROPERTY_EXTRA_FIXED,
  RouteOptimizationOvertimeCost.JSON_PROPERTY_EXTRA_PER_HOUR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-19T11:48:12.214027216Z[Etc/UTC]", comments = "Generator version: 7.5.0")
public class RouteOptimizationOvertimeCost {
  public static final String JSON_PROPERTY_THRESHOLD = "threshold";
  private Integer threshold;

  public static final String JSON_PROPERTY_EXTRA_FIXED = "extraFixed";
  private Double extraFixed = 0d;

  public static final String JSON_PROPERTY_EXTRA_PER_HOUR = "extraPerHour";
  private Double extraPerHour = 0d;

  public RouteOptimizationOvertimeCost() { 
  }

  public RouteOptimizationOvertimeCost threshold(Integer threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * The threshold for the route duration [s] above which the extra costs apply.
   * minimum: 0
   * @return threshold
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getThreshold() {
    return threshold;
  }


  @JsonProperty(JSON_PROPERTY_THRESHOLD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThreshold(Integer threshold) {
    this.threshold = threshold;
  }


  public RouteOptimizationOvertimeCost extraFixed(Double extraFixed) {
    this.extraFixed = extraFixed;
    return this;
  }

   /**
   * Specifies the extra fixed cost when exceeding the threshold.
   * minimum: 0
   * @return extraFixed
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA_FIXED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getExtraFixed() {
    return extraFixed;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_FIXED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtraFixed(Double extraFixed) {
    this.extraFixed = extraFixed;
  }


  public RouteOptimizationOvertimeCost extraPerHour(Double extraPerHour) {
    this.extraPerHour = extraPerHour;
    return this;
  }

   /**
   * Specifies the extra cost for every hour above the threshold.
   * minimum: 0
   * @return extraPerHour
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA_PER_HOUR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getExtraPerHour() {
    return extraPerHour;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_PER_HOUR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtraPerHour(Double extraPerHour) {
    this.extraPerHour = extraPerHour;
  }


  /**
   * Return true if this OvertimeCost object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteOptimizationOvertimeCost overtimeCost = (RouteOptimizationOvertimeCost) o;
    return Objects.equals(this.threshold, overtimeCost.threshold) &&
        Objects.equals(this.extraFixed, overtimeCost.extraFixed) &&
        Objects.equals(this.extraPerHour, overtimeCost.extraPerHour);
  }

  @Override
  public int hashCode() {
    return Objects.hash(threshold, extraFixed, extraPerHour);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteOptimizationOvertimeCost {\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    extraFixed: ").append(toIndentedString(extraFixed)).append("\n");
    sb.append("    extraPerHour: ").append(toIndentedString(extraPerHour)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `threshold` to the URL query string
    if (getThreshold() != null) {
      joiner.add(String.format("%sthreshold%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getThreshold()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `extraFixed` to the URL query string
    if (getExtraFixed() != null) {
      joiner.add(String.format("%sextraFixed%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExtraFixed()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `extraPerHour` to the URL query string
    if (getExtraPerHour() != null) {
      joiner.add(String.format("%sextraPerHour%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExtraPerHour()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

