/*
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.39
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routeoptimization.optiflow.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.routeoptimization.optiflow.model.RouteOptimizationBatteryConsumption;
import com.ptvgroup.developer.client.routeoptimization.optiflow.model.RouteOptimizationBatteryStateOfCharge;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Physical properties of the battery of an electric vehicle. Check your individual price plan or contract to see whether or not the request may contain a battery.
 */
@JsonPropertyOrder({
  RouteOptimizationVehicleBattery.JSON_PROPERTY_CAPACITY,
  RouteOptimizationVehicleBattery.JSON_PROPERTY_STATE_OF_CHARGE,
  RouteOptimizationVehicleBattery.JSON_PROPERTY_CONSUMPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-19T11:48:12.214027216Z[Etc/UTC]", comments = "Generator version: 7.5.0")
public class RouteOptimizationVehicleBattery {
  public static final String JSON_PROPERTY_CAPACITY = "capacity";
  private Double capacity;

  public static final String JSON_PROPERTY_STATE_OF_CHARGE = "stateOfCharge";
  private RouteOptimizationBatteryStateOfCharge stateOfCharge;

  public static final String JSON_PROPERTY_CONSUMPTION = "consumption";
  private RouteOptimizationBatteryConsumption consumption;

  public RouteOptimizationVehicleBattery() { 
  }

  public RouteOptimizationVehicleBattery capacity(Double capacity) {
    this.capacity = capacity;
    return this;
  }

   /**
   * The total battery capacity [kWh].
   * minimum: 0
   * maximum: 10000
   * @return capacity
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getCapacity() {
    return capacity;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCapacity(Double capacity) {
    this.capacity = capacity;
  }


  public RouteOptimizationVehicleBattery stateOfCharge(RouteOptimizationBatteryStateOfCharge stateOfCharge) {
    this.stateOfCharge = stateOfCharge;
    return this;
  }

   /**
   * Get stateOfCharge
   * @return stateOfCharge
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE_OF_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RouteOptimizationBatteryStateOfCharge getStateOfCharge() {
    return stateOfCharge;
  }


  @JsonProperty(JSON_PROPERTY_STATE_OF_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStateOfCharge(RouteOptimizationBatteryStateOfCharge stateOfCharge) {
    this.stateOfCharge = stateOfCharge;
  }


  public RouteOptimizationVehicleBattery consumption(RouteOptimizationBatteryConsumption consumption) {
    this.consumption = consumption;
    return this;
  }

   /**
   * Get consumption
   * @return consumption
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONSUMPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RouteOptimizationBatteryConsumption getConsumption() {
    return consumption;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsumption(RouteOptimizationBatteryConsumption consumption) {
    this.consumption = consumption;
  }


  /**
   * Return true if this VehicleBattery object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteOptimizationVehicleBattery vehicleBattery = (RouteOptimizationVehicleBattery) o;
    return Objects.equals(this.capacity, vehicleBattery.capacity) &&
        Objects.equals(this.stateOfCharge, vehicleBattery.stateOfCharge) &&
        Objects.equals(this.consumption, vehicleBattery.consumption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capacity, stateOfCharge, consumption);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteOptimizationVehicleBattery {\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    stateOfCharge: ").append(toIndentedString(stateOfCharge)).append("\n");
    sb.append("    consumption: ").append(toIndentedString(consumption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `capacity` to the URL query string
    if (getCapacity() != null) {
      joiner.add(String.format("%scapacity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCapacity()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `stateOfCharge` to the URL query string
    if (getStateOfCharge() != null) {
      joiner.add(getStateOfCharge().toUrlQueryString(prefix + "stateOfCharge" + suffix));
    }

    // add `consumption` to the URL query string
    if (getConsumption() != null) {
      joiner.add(getConsumption().toUrlQueryString(prefix + "consumption" + suffix));
    }

    return joiner.toString();
  }
}

