/*
 * OptiFlow
 *
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.Model
{
    /// <summary>
    /// Describes which combination of depots and vehicles have to be respected or excluded. * DEPOT_REQUIRES_VEHICLE - A depot from the given depot category can only be visited by a vehicle from the given vehicle category. * VEHICLE_REQUIRES_DEPOT - A vehicle from the given vehicle category can only visit depots from the given depot category.  * FORBIDDEN_COMBINATION - A depot from the given depot category can not be visited by a vehicle from the given vehicle category. 
    /// </summary>
    /// <value>Describes which combination of depots and vehicles have to be respected or excluded. * DEPOT_REQUIRES_VEHICLE - A depot from the given depot category can only be visited by a vehicle from the given vehicle category. * VEHICLE_REQUIRES_DEPOT - A vehicle from the given vehicle category can only visit depots from the given depot category.  * FORBIDDEN_COMBINATION - A depot from the given depot category can not be visited by a vehicle from the given vehicle category. </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DepotVehicleCombinationConstraintType
    {
        /// <summary>
        /// Enum DEPOT_REQUIRES_VEHICLE for value: DEPOT_REQUIRES_VEHICLE
        /// </summary>
        [EnumMember(Value = "DEPOT_REQUIRES_VEHICLE")]
        DEPOT_REQUIRES_VEHICLE = 1,

        /// <summary>
        /// Enum VEHICLE_REQUIRES_DEPOT for value: VEHICLE_REQUIRES_DEPOT
        /// </summary>
        [EnumMember(Value = "VEHICLE_REQUIRES_DEPOT")]
        VEHICLE_REQUIRES_DEPOT = 2,

        /// <summary>
        /// Enum FORBIDDEN_COMBINATION for value: FORBIDDEN_COMBINATION
        /// </summary>
        [EnumMember(Value = "FORBIDDEN_COMBINATION")]
        FORBIDDEN_COMBINATION = 3

    }

}
