/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderVehicleCombinationConstraintType,
    OrderVehicleCombinationConstraintTypeFromJSON,
    OrderVehicleCombinationConstraintTypeFromJSONTyped,
    OrderVehicleCombinationConstraintTypeToJSON,
} from './OrderVehicleCombinationConstraintType';

/**
 * A constraint on the combination of orders and vehicles belonging to a certain category.
 * @export
 * @interface OrderVehicleCombinationConstraint
 */
export interface OrderVehicleCombinationConstraint {
    /**
     * 
     * @type {OrderVehicleCombinationConstraintType}
     * @memberof OrderVehicleCombinationConstraint
     */
    type: OrderVehicleCombinationConstraintType;
    /**
     * The category of orders to which the constraint applies. The constraint will be ignored if no order belongs to this category.
     * @type {string}
     * @memberof OrderVehicleCombinationConstraint
     */
    orderCategory: string;
    /**
     * The category of vehicles to which the constraint applies. The constraint will be ignored if no vehicle belongs to this category.
     * @type {string}
     * @memberof OrderVehicleCombinationConstraint
     */
    vehicleCategory: string;
}

export function OrderVehicleCombinationConstraintFromJSON(json: any): OrderVehicleCombinationConstraint {
    return OrderVehicleCombinationConstraintFromJSONTyped(json, false);
}

export function OrderVehicleCombinationConstraintFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderVehicleCombinationConstraint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': OrderVehicleCombinationConstraintTypeFromJSON(json['type']),
        'orderCategory': json['orderCategory'],
        'vehicleCategory': json['vehicleCategory'],
    };
}

export function OrderVehicleCombinationConstraintToJSON(value?: OrderVehicleCombinationConstraint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': OrderVehicleCombinationConstraintTypeToJSON(value.type),
        'orderCategory': value.orderCategory,
        'vehicleCategory': value.vehicleCategory,
    };
}

