/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderProperties,
    OrderPropertiesFromJSON,
    OrderPropertiesFromJSONTyped,
    OrderPropertiesToJSON,
} from './OrderProperties';
import {
    TaskProperties,
    TaskPropertiesFromJSON,
    TaskPropertiesFromJSONTyped,
    TaskPropertiesToJSON,
} from './TaskProperties';

/**
 * A request to pickup an order and transport it to a depot.
 * @export
 * @interface PickupOrder
 */
export interface PickupOrder {
    /**
     * A unique identifier of the order. This must be unique across all orders.
     * @type {string}
     * @memberof PickupOrder
     */
    id: string;
    /**
     * 
     * @type {TaskProperties}
     * @memberof PickupOrder
     */
    pickup: TaskProperties;
    /**
     * 
     * @type {OrderProperties}
     * @memberof PickupOrder
     */
    properties?: OrderProperties;
}

export function PickupOrderFromJSON(json: any): PickupOrder {
    return PickupOrderFromJSONTyped(json, false);
}

export function PickupOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pickup': TaskPropertiesFromJSON(json['pickup']),
        'properties': !exists(json, 'properties') ? undefined : OrderPropertiesFromJSON(json['properties']),
    };
}

export function PickupOrderToJSON(value?: PickupOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'pickup': TaskPropertiesToJSON(value.pickup),
        'properties': OrderPropertiesToJSON(value.properties),
    };
}

