/* tslint:disable */
/* eslint-disable */
/**
 * OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A sequence that must be respected when scheduling routes. Tasks with a category that occurs earlier in the sequence must be scheduled in the route before a task with a category later in the sequence.
 * @export
 * @interface RespectedTaskSequence
 */
export interface RespectedTaskSequence {
    /**
     * The sequence of task categories that needs to be respected within a route. The index of the category in the list determines the sequence. Categories that do not correspond to any task are ignored.
     * @type {Set<string>}
     * @memberof RespectedTaskSequence
     */
    taskCategories: Set<string>;
    /**
     * The category of vehicles to which this constraint applies. When omitted the constraint applies to all vehicles. The constraint will be ignored when no vehicle belongs to this category.
     * @type {string}
     * @memberof RespectedTaskSequence
     */
    vehicleCategory?: string;
}

export function RespectedTaskSequenceFromJSON(json: any): RespectedTaskSequence {
    return RespectedTaskSequenceFromJSONTyped(json, false);
}

export function RespectedTaskSequenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RespectedTaskSequence {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskCategories': json['taskCategories'],
        'vehicleCategory': !exists(json, 'vehicleCategory') ? undefined : json['vehicleCategory'],
    };
}

export function RespectedTaskSequenceToJSON(value?: RespectedTaskSequence | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taskCategories': value.taskCategories,
        'vehicleCategory': value.vehicleCategory,
    };
}

