/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RouteOptimizationBreakStructure } from './RouteOptimizationBreakStructure';
import {
    RouteOptimizationBreakStructureFromJSON,
    RouteOptimizationBreakStructureFromJSONTyped,
    RouteOptimizationBreakStructureToJSON,
} from './RouteOptimizationBreakStructure';
import type { RouteOptimizationChargingStructure } from './RouteOptimizationChargingStructure';
import {
    RouteOptimizationChargingStructureFromJSON,
    RouteOptimizationChargingStructureFromJSONTyped,
    RouteOptimizationChargingStructureToJSON,
} from './RouteOptimizationChargingStructure';
import type { RouteOptimizationTaskStructure } from './RouteOptimizationTaskStructure';
import {
    RouteOptimizationTaskStructureFromJSON,
    RouteOptimizationTaskStructureFromJSONTyped,
    RouteOptimizationTaskStructureToJSON,
} from './RouteOptimizationTaskStructure';

/**
 * A description of the route structure that can be used to reconstruct the route.
 * @export
 * @interface RouteOptimizationRouteStructure
 */
export interface RouteOptimizationRouteStructure {
    /**
     * The unique identifier of the vehicle that is used to execute the route. Only a single route can be provided for each vehicle.
     * @type {string}
     * @memberof RouteOptimizationRouteStructure
     */
    vehicleId: string;
    /**
     * The unique identifiers of the resources assigned to the vehicle executing the route.
     * @type {Set<string>}
     * @memberof RouteOptimizationRouteStructure
     */
    resourceIds?: Set<string>;
    /**
     * The point in time when the route should start. The start time will be respected as closely as possible.
     * Formatted according to [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6). The date must not be before `1970-01-01T00:00:00+00:00` nor after `2037-12-31T23:59:59+00:00`. The date must provide an offset to UTC.
     * @type {Date}
     * @memberof RouteOptimizationRouteStructure
     */
    start: Date;
    /**
     * The unique identifier of the location where the route starts. This must either be the provided start location of the vehicle, the location of the first stop when the vehicle has no fixed start location or a layover location. When omitted, the location will be automatically inferred, assuming a layover does not occur before this route.
     * @type {string}
     * @memberof RouteOptimizationRouteStructure
     */
    startLocationId?: string;
    /**
     * The unique identifier of the location where the route ends. This must either be the provided end location of the vehicle, the location of the last stop when the vehicle has no fixed end location or a layover location. When omitted, the location will be automatically inferred, assuming a layover does not occur after this route.
     * @type {string}
     * @memberof RouteOptimizationRouteStructure
     */
    endLocationId?: string;
    /**
     * A sequence of tasks scheduled on the route.
     * @type {Array<RouteOptimizationTaskStructure>}
     * @memberof RouteOptimizationRouteStructure
     */
    tasks?: Array<RouteOptimizationTaskStructure>;
    /**
     * A list of breaks scheduled on the route.
     * When omitted, reconstruction will make a best effort to schedule breaks in order to satisfy the break settings.
     * @type {Array<RouteOptimizationBreakStructure>}
     * @memberof RouteOptimizationRouteStructure
     */
    breaks?: Array<RouteOptimizationBreakStructure>;
    /**
     * A list of charging times scheduled on the route.
     * When omitted, reconstruction will make a best effort to schedule charging in order to satisfy the vehicle’s requirements.
     * @type {Array<RouteOptimizationChargingStructure>}
     * @memberof RouteOptimizationRouteStructure
     */
    charging?: Array<RouteOptimizationChargingStructure>;
}

/**
 * Check if a given object implements the RouteOptimizationRouteStructure interface.
 */
export function instanceOfRouteOptimizationRouteStructure(value: object): boolean {
    if (!('vehicleId' in value)) return false;
    if (!('start' in value)) return false;
    return true;
}

export function RouteOptimizationRouteStructureFromJSON(json: any): RouteOptimizationRouteStructure {
    return RouteOptimizationRouteStructureFromJSONTyped(json, false);
}

export function RouteOptimizationRouteStructureFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationRouteStructure {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicleId': json['vehicleId'],
        'resourceIds': json['resourceIds'] == null ? undefined : json['resourceIds'],
        'start': (new Date(json['start'])),
        'startLocationId': json['startLocationId'] == null ? undefined : json['startLocationId'],
        'endLocationId': json['endLocationId'] == null ? undefined : json['endLocationId'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(RouteOptimizationTaskStructureFromJSON)),
        'breaks': json['breaks'] == null ? undefined : ((json['breaks'] as Array<any>).map(RouteOptimizationBreakStructureFromJSON)),
        'charging': json['charging'] == null ? undefined : ((json['charging'] as Array<any>).map(RouteOptimizationChargingStructureFromJSON)),
    };
}

export function RouteOptimizationRouteStructureToJSON(value?: RouteOptimizationRouteStructure | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'vehicleId': value['vehicleId'],
        'resourceIds': value['resourceIds'] == null ? undefined : Array.from(value['resourceIds'] as Set<any>),
        'start': ((value['start']).toISOString()),
        'startLocationId': value['startLocationId'],
        'endLocationId': value['endLocationId'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(RouteOptimizationTaskStructureToJSON)),
        'breaks': value['breaks'] == null ? undefined : ((value['breaks'] as Array<any>).map(RouteOptimizationBreakStructureToJSON)),
        'charging': value['charging'] == null ? undefined : ((value['charging'] as Array<any>).map(RouteOptimizationChargingStructureToJSON)),
    };
}

