/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.42
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A summary of the key parameters from the optimization request, providing an overview of the problem size and constraints.
 * @export
 * @interface RouteOptimizationRequestSummary
 */
export interface RouteOptimizationRequestSummary {
    /**
     * The maximum duration [s] of the optimization.
     * @type {number}
     * @memberof RouteOptimizationRequestSummary
     */
    duration: number;
    /**
     * The number of locations.
     * @type {number}
     * @memberof RouteOptimizationRequestSummary
     */
    numberOfLocations: number;
    /**
     * The number of orders.
     * @type {number}
     * @memberof RouteOptimizationRequestSummary
     */
    numberOfOrders: number;
    /**
     * The number of vehicles.
     * @type {number}
     * @memberof RouteOptimizationRequestSummary
     */
    numberOfVehicles: number;
    /**
     * The number of resources.
     * @type {number}
     * @memberof RouteOptimizationRequestSummary
     */
    numberOfResources: number;
    /**
     * The number of depots.
     * @type {number}
     * @memberof RouteOptimizationRequestSummary
     */
    numberOfDepots: number;
}

/**
 * Check if a given object implements the RouteOptimizationRequestSummary interface.
 */
export function instanceOfRouteOptimizationRequestSummary(value: object): boolean {
    if (!('duration' in value)) return false;
    if (!('numberOfLocations' in value)) return false;
    if (!('numberOfOrders' in value)) return false;
    if (!('numberOfVehicles' in value)) return false;
    if (!('numberOfResources' in value)) return false;
    if (!('numberOfDepots' in value)) return false;
    return true;
}

export function RouteOptimizationRequestSummaryFromJSON(json: any): RouteOptimizationRequestSummary {
    return RouteOptimizationRequestSummaryFromJSONTyped(json, false);
}

export function RouteOptimizationRequestSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationRequestSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'numberOfLocations': json['numberOfLocations'],
        'numberOfOrders': json['numberOfOrders'],
        'numberOfVehicles': json['numberOfVehicles'],
        'numberOfResources': json['numberOfResources'],
        'numberOfDepots': json['numberOfDepots'],
    };
}

export function RouteOptimizationRequestSummaryToJSON(value?: RouteOptimizationRequestSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'duration': value['duration'],
        'numberOfLocations': value['numberOfLocations'],
        'numberOfOrders': value['numberOfOrders'],
        'numberOfVehicles': value['numberOfVehicles'],
        'numberOfResources': value['numberOfResources'],
        'numberOfDepots': value['numberOfDepots'],
    };
}

