/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.42
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes the strategy for loading and unloading orders in the compartment.
 * * `NONE` - There is no restriction on the sequence of loading or unloading.
 * * `LAST_IN_FIRST_OUT` - The last order loaded must be the first to be unloaded.
 * @export
 */
export const RouteOptimizationCompartmentLoadingStrategy = {
    NONE: 'NONE',
    LAST_IN_FIRST_OUT: 'LAST_IN_FIRST_OUT'
} as const;
export type RouteOptimizationCompartmentLoadingStrategy = typeof RouteOptimizationCompartmentLoadingStrategy[keyof typeof RouteOptimizationCompartmentLoadingStrategy];


export function instanceOfRouteOptimizationCompartmentLoadingStrategy(value: any): boolean {
    return Object.values(RouteOptimizationCompartmentLoadingStrategy).includes(value);
}

export function RouteOptimizationCompartmentLoadingStrategyFromJSON(json: any): RouteOptimizationCompartmentLoadingStrategy {
    return RouteOptimizationCompartmentLoadingStrategyFromJSONTyped(json, false);
}

export function RouteOptimizationCompartmentLoadingStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationCompartmentLoadingStrategy {
    return json as RouteOptimizationCompartmentLoadingStrategy;
}

export function RouteOptimizationCompartmentLoadingStrategyToJSON(value?: RouteOptimizationCompartmentLoadingStrategy | null): any {
    return value as any;
}

