/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.39
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * General settings of the optimization.
 * @export
 * @interface RouteOptimizationOptimizationSettings
 */
export interface RouteOptimizationOptimizationSettings {
    /**
     * Defines the maximum duration [s] the optimization can use to reduce the cost of the scheduled routes.
     * Please note that the upper bound on optimization duration is a technical limit. Check your individual price plan or contract to see which limits apply. The optimization will automatically stop when this duration is spent in the `RUNNING` status but can also be stopped manually using the *stopOptimization* endpoint.
     * @type {number}
     * @memberof RouteOptimizationOptimizationSettings
     */
    duration: number;
    /**
     * Defines the maximum duration [s] the optimization may continue without improving the best-known solution.
     * If no better solution is found within this period, the optimization will stop early - even if the overall duration limit has not yet been reached. This mechanism helps reduce unnecessary computation time when progress stalls. The stagnation timer starts when the optimization enters the `RUNNING` status and resets each time a better solution is found.
     * *Use with caution:* This feature may prematurely terminate optimizations that could still yield better solutions given more time. Since the timing of improvements is inherently unpredictable, relying on this setting can lead to suboptimal results. It is recommended to disable this feature or set a conservative value unless you have strong reasons to limit runtime based on stagnation.
     * @type {number}
     * @memberof RouteOptimizationOptimizationSettings
     */
    maximumStagnationDuration?: number;
}

/**
 * Check if a given object implements the RouteOptimizationOptimizationSettings interface.
 */
export function instanceOfRouteOptimizationOptimizationSettings(value: object): boolean {
    if (!('duration' in value)) return false;
    return true;
}

export function RouteOptimizationOptimizationSettingsFromJSON(json: any): RouteOptimizationOptimizationSettings {
    return RouteOptimizationOptimizationSettingsFromJSONTyped(json, false);
}

export function RouteOptimizationOptimizationSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationOptimizationSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'maximumStagnationDuration': json['maximumStagnationDuration'] == null ? undefined : json['maximumStagnationDuration'],
    };
}

export function RouteOptimizationOptimizationSettingsToJSON(value?: RouteOptimizationOptimizationSettings | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'duration': value['duration'],
        'maximumStagnationDuration': value['maximumStagnationDuration'],
    };
}

