/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.68
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An order that is already loaded onto the vehicle, requiring only delivery.
 * @export
 * @interface RouteOptimizationLoadedOrder
 */
export interface RouteOptimizationLoadedOrder {
    /**
     * The unique identifier of the loaded order. Must not belong to a service.
     * @type {string}
     * @memberof RouteOptimizationLoadedOrder
     */
    orderId: string;
    /**
     * The compartment the order is loaded in. Required if the vehicle has compartments.
     * @type {string}
     * @memberof RouteOptimizationLoadedOrder
     */
    compartmentId?: string;
}

/**
 * Check if a given object implements the RouteOptimizationLoadedOrder interface.
 */
export function instanceOfRouteOptimizationLoadedOrder(value: object): boolean {
    if (!('orderId' in value)) return false;
    return true;
}

export function RouteOptimizationLoadedOrderFromJSON(json: any): RouteOptimizationLoadedOrder {
    return RouteOptimizationLoadedOrderFromJSONTyped(json, false);
}

export function RouteOptimizationLoadedOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationLoadedOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'compartmentId': json['compartmentId'] == null ? undefined : json['compartmentId'],
    };
}

export function RouteOptimizationLoadedOrderToJSON(value?: RouteOptimizationLoadedOrder | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'orderId': value['orderId'],
        'compartmentId': value['compartmentId'],
    };
}

