/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.69
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Restricts the maximum distance a vehicle may travel on a single approach: the leg by which it reaches a stop, or the route's end location. The constraint applies to an approach whose start location matches the start location category and whose end location matches the end location category. Optionally filtered to vehicles matching a vehicle category.
 * @export
 * @interface RouteOptimizationMaximumApproachDistanceLocationConstraint
 */
export interface RouteOptimizationMaximumApproachDistanceLocationConstraint {
    /**
     * The constraint applies only to approaches whose start location matches this category. If this field contains a plain category name (e.g. `CATEGORY_A`), it matches locations that have this category. If this field starts with `!` (e.g. `!CATEGORY_A`), it matches locations that **do not** have that category. The constraint will be ignored if no location belongs to this category.
     * @type {string}
     * @memberof RouteOptimizationMaximumApproachDistanceLocationConstraint
     */
    startLocationCategory: string;
    /**
     * The constraint applies only to approaches whose end location matches this category. If this field contains a plain category name (e.g. `CATEGORY_A`), it matches locations that have this category. If this field starts with `!` (e.g. `!CATEGORY_A`), it matches locations that **do not** have that category. The constraint will be ignored if no location belongs to this category.
     * @type {string}
     * @memberof RouteOptimizationMaximumApproachDistanceLocationConstraint
     */
    endLocationCategory: string;
    /**
     * The maximum distance [m] a vehicle may travel on a matching approach.
     * @type {number}
     * @memberof RouteOptimizationMaximumApproachDistanceLocationConstraint
     */
    value: number;
    /**
     * The constraint applies only to vehicles that match this category. When omitted, the constraint applies to all vehicles. If this field contains a plain category name (e.g. `CATEGORY_A`), it matches vehicles that have this category. If this field starts with `!` (e.g. `!CATEGORY_A`), it matches vehicles that **do not** have that category. If no vehicle matches this condition, the constraint is ignored.
     * @type {string}
     * @memberof RouteOptimizationMaximumApproachDistanceLocationConstraint
     */
    vehicleCategory?: string;
}

/**
 * Check if a given object implements the RouteOptimizationMaximumApproachDistanceLocationConstraint interface.
 */
export function instanceOfRouteOptimizationMaximumApproachDistanceLocationConstraint(value: object): boolean {
    if (!('startLocationCategory' in value)) return false;
    if (!('endLocationCategory' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function RouteOptimizationMaximumApproachDistanceLocationConstraintFromJSON(json: any): RouteOptimizationMaximumApproachDistanceLocationConstraint {
    return RouteOptimizationMaximumApproachDistanceLocationConstraintFromJSONTyped(json, false);
}

export function RouteOptimizationMaximumApproachDistanceLocationConstraintFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationMaximumApproachDistanceLocationConstraint {
    if (json == null) {
        return json;
    }
    return {
        
        'startLocationCategory': json['startLocationCategory'],
        'endLocationCategory': json['endLocationCategory'],
        'value': json['value'],
        'vehicleCategory': json['vehicleCategory'] == null ? undefined : json['vehicleCategory'],
    };
}

export function RouteOptimizationMaximumApproachDistanceLocationConstraintToJSON(value?: RouteOptimizationMaximumApproachDistanceLocationConstraint | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'startLocationCategory': value['startLocationCategory'],
        'endLocationCategory': value['endLocationCategory'],
        'value': value['value'],
        'vehicleCategory': value['vehicleCategory'],
    };
}

