/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.61
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes the kWh consumption for a specific dimension.
 * @export
 * @interface RouteOptimizationLoadBatteryConsumption
 */
export interface RouteOptimizationLoadBatteryConsumption {
    /**
     * Indicates the specific dimension of the load, such as its volume, weight, or size.
     * @type {string}
     * @memberof RouteOptimizationLoadBatteryConsumption
     */
    dimension: string;
    /**
     * Describes the kWh consumed by transporting a single unit of the specified dimension for 100km.
     * @type {number}
     * @memberof RouteOptimizationLoadBatteryConsumption
     */
    perUnitPerHundredKilometers: number;
}

/**
 * Check if a given object implements the RouteOptimizationLoadBatteryConsumption interface.
 */
export function instanceOfRouteOptimizationLoadBatteryConsumption(value: object): boolean {
    if (!('dimension' in value)) return false;
    if (!('perUnitPerHundredKilometers' in value)) return false;
    return true;
}

export function RouteOptimizationLoadBatteryConsumptionFromJSON(json: any): RouteOptimizationLoadBatteryConsumption {
    return RouteOptimizationLoadBatteryConsumptionFromJSONTyped(json, false);
}

export function RouteOptimizationLoadBatteryConsumptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationLoadBatteryConsumption {
    if (json == null) {
        return json;
    }
    return {
        
        'dimension': json['dimension'],
        'perUnitPerHundredKilometers': json['perUnitPerHundredKilometers'],
    };
}

export function RouteOptimizationLoadBatteryConsumptionToJSON(value?: RouteOptimizationLoadBatteryConsumption | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dimension': value['dimension'],
        'perUnitPerHundredKilometers': value['perUnitPerHundredKilometers'],
    };
}

