/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.39
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RouteOptimizationRouteCosts } from './RouteOptimizationRouteCosts';
import {
    RouteOptimizationRouteCostsFromJSON,
    RouteOptimizationRouteCostsFromJSONTyped,
    RouteOptimizationRouteCostsToJSON,
} from './RouteOptimizationRouteCosts';
import type { RouteOptimizationRouteDurations } from './RouteOptimizationRouteDurations';
import {
    RouteOptimizationRouteDurationsFromJSON,
    RouteOptimizationRouteDurationsFromJSONTyped,
    RouteOptimizationRouteDurationsToJSON,
} from './RouteOptimizationRouteDurations';

/**
 * Metrics providing insights into the route.
 * @export
 * @interface RouteOptimizationRouteMetrics
 */
export interface RouteOptimizationRouteMetrics {
    /**
     * The number of stops in the route. A stop is a visit at a location where one or more tasks are executed.
     * @type {number}
     * @memberof RouteOptimizationRouteMetrics
     */
    numberOfStops?: number;
    /**
     * The number of orders scheduled on the route.
     * @type {number}
     * @memberof RouteOptimizationRouteMetrics
     */
    numberOfOrders?: number;
    /**
     * The cost of the route. This includes the cost per hour, cost per kilometer and fixed cost of the vehicle.
     * @type {number}
     * @memberof RouteOptimizationRouteMetrics
     * @deprecated
     */
    cost?: number;
    /**
     * 
     * @type {RouteOptimizationRouteCosts}
     * @memberof RouteOptimizationRouteMetrics
     */
    costs?: RouteOptimizationRouteCosts;
    /**
     * The distance [m] travelled on the route.
     * @type {number}
     * @memberof RouteOptimizationRouteMetrics
     */
    distance?: number;
    /**
     * The duration [s] of the route from start to end.
     * @type {number}
     * @memberof RouteOptimizationRouteMetrics
     * @deprecated
     */
    duration?: number;
    /**
     * 
     * @type {RouteOptimizationRouteDurations}
     * @memberof RouteOptimizationRouteMetrics
     */
    durations?: RouteOptimizationRouteDurations;
}

/**
 * Check if a given object implements the RouteOptimizationRouteMetrics interface.
 */
export function instanceOfRouteOptimizationRouteMetrics(value: object): boolean {
    return true;
}

export function RouteOptimizationRouteMetricsFromJSON(json: any): RouteOptimizationRouteMetrics {
    return RouteOptimizationRouteMetricsFromJSONTyped(json, false);
}

export function RouteOptimizationRouteMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationRouteMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfStops': json['numberOfStops'] == null ? undefined : json['numberOfStops'],
        'numberOfOrders': json['numberOfOrders'] == null ? undefined : json['numberOfOrders'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'costs': json['costs'] == null ? undefined : RouteOptimizationRouteCostsFromJSON(json['costs']),
        'distance': json['distance'] == null ? undefined : json['distance'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'durations': json['durations'] == null ? undefined : RouteOptimizationRouteDurationsFromJSON(json['durations']),
    };
}

export function RouteOptimizationRouteMetricsToJSON(value?: RouteOptimizationRouteMetrics | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'numberOfStops': value['numberOfStops'],
        'numberOfOrders': value['numberOfOrders'],
        'cost': value['cost'],
        'costs': RouteOptimizationRouteCostsToJSON(value['costs']),
        'distance': value['distance'],
        'duration': value['duration'],
        'durations': RouteOptimizationRouteDurationsToJSON(value['durations']),
    };
}

