/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.61
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines a cost that is applied per batch of load handled at a depot for a specific dimension.
 * @export
 * @interface RouteOptimizationDepotLoadCost
 */
export interface RouteOptimizationDepotLoadCost {
    /**
     * Indicates the specific dimension of the load, such as its volume, weight, or size.
     * @type {string}
     * @memberof RouteOptimizationDepotLoadCost
     */
    dimension: string;
    /**
     * The size of a batch for which the cost is applied.
     * @type {number}
     * @memberof RouteOptimizationDepotLoadCost
     */
    batchSize: number;
    /**
     * The cost incurred for each batch of load handled at the depot.
     * @type {number}
     * @memberof RouteOptimizationDepotLoadCost
     */
    costPerBatch: number;
    /**
     * The cost applies only to orders whose categories match this condition. When omitted, the cost applies to all orders. If this field contains a plain category name (e.g. `CATEGORY_A`), it matches orders that have this category. If this field starts with `!` (e.g. `!CATEGORY_A`), it matches orders that **do not** have that category.
     * @type {string}
     * @memberof RouteOptimizationDepotLoadCost
     */
    orderCategory?: string;
}

/**
 * Check if a given object implements the RouteOptimizationDepotLoadCost interface.
 */
export function instanceOfRouteOptimizationDepotLoadCost(value: object): boolean {
    if (!('dimension' in value)) return false;
    if (!('batchSize' in value)) return false;
    if (!('costPerBatch' in value)) return false;
    return true;
}

export function RouteOptimizationDepotLoadCostFromJSON(json: any): RouteOptimizationDepotLoadCost {
    return RouteOptimizationDepotLoadCostFromJSONTyped(json, false);
}

export function RouteOptimizationDepotLoadCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationDepotLoadCost {
    if (json == null) {
        return json;
    }
    return {
        
        'dimension': json['dimension'],
        'batchSize': json['batchSize'],
        'costPerBatch': json['costPerBatch'],
        'orderCategory': json['orderCategory'] == null ? undefined : json['orderCategory'],
    };
}

export function RouteOptimizationDepotLoadCostToJSON(value?: RouteOptimizationDepotLoadCost | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dimension': value['dimension'],
        'batchSize': value['batchSize'],
        'costPerBatch': value['costPerBatch'],
        'orderCategory': value['orderCategory'],
    };
}

