/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines an extra cost that is applied whenever an order is loaded onto the vehicle and the vehicle's load exceeds the specified threshold.
 * @export
 * @interface RouteOptimizationOverloadCost
 */
export interface RouteOptimizationOverloadCost {
    /**
     * Indicates the dimension of the load, to which the threshold applies.
     * @type {string}
     * @memberof RouteOptimizationOverloadCost
     */
    dimension: string;
    /**
     * The threshold for the specified load dimension.  When an order is loaded, only the part of that order which contributes to exceeding the threshold is considered for the extra cost.
     * @type {number}
     * @memberof RouteOptimizationOverloadCost
     */
    threshold: number;
    /**
     * Specifies the extra cost per unit when loading an order which exceeds the threshold.
     * @type {number}
     * @memberof RouteOptimizationOverloadCost
     */
    extraPerUnit: number;
}

/**
 * Check if a given object implements the RouteOptimizationOverloadCost interface.
 */
export function instanceOfRouteOptimizationOverloadCost(value: object): boolean {
    if (!('dimension' in value)) return false;
    if (!('threshold' in value)) return false;
    if (!('extraPerUnit' in value)) return false;
    return true;
}

export function RouteOptimizationOverloadCostFromJSON(json: any): RouteOptimizationOverloadCost {
    return RouteOptimizationOverloadCostFromJSONTyped(json, false);
}

export function RouteOptimizationOverloadCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationOverloadCost {
    if (json == null) {
        return json;
    }
    return {
        
        'dimension': json['dimension'],
        'threshold': json['threshold'],
        'extraPerUnit': json['extraPerUnit'],
    };
}

export function RouteOptimizationOverloadCostToJSON(value?: RouteOptimizationOverloadCost | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dimension': value['dimension'],
        'threshold': value['threshold'],
        'extraPerUnit': value['extraPerUnit'],
    };
}

