/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.62
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes the vehicle's battery energy level before and after a charging event.
 * @export
 * @interface RouteOptimizationChargingStateOfCharge
 */
export interface RouteOptimizationChargingStateOfCharge {
    /**
     * The battery energy level immediately before charging begins, expressed as a fraction of total capacity (0.0 = empty, 1.0 = fully charged).
     * @type {number}
     * @memberof RouteOptimizationChargingStateOfCharge
     */
    before?: number;
    /**
     * The battery energy level immediately after charging has finished, expressed as a fraction of total capacity (0.0 = empty, 1.0 = fully charged).
     * @type {number}
     * @memberof RouteOptimizationChargingStateOfCharge
     */
    after?: number;
}

/**
 * Check if a given object implements the RouteOptimizationChargingStateOfCharge interface.
 */
export function instanceOfRouteOptimizationChargingStateOfCharge(value: object): boolean {
    return true;
}

export function RouteOptimizationChargingStateOfChargeFromJSON(json: any): RouteOptimizationChargingStateOfCharge {
    return RouteOptimizationChargingStateOfChargeFromJSONTyped(json, false);
}

export function RouteOptimizationChargingStateOfChargeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationChargingStateOfCharge {
    if (json == null) {
        return json;
    }
    return {
        
        'before': json['before'] == null ? undefined : json['before'],
        'after': json['after'] == null ? undefined : json['after'],
    };
}

export function RouteOptimizationChargingStateOfChargeToJSON(value?: RouteOptimizationChargingStateOfCharge | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'before': value['before'],
        'after': value['after'],
    };
}

