/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.58
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RouteOptimizationDepotLoadCost } from './RouteOptimizationDepotLoadCost';
import {
    RouteOptimizationDepotLoadCostFromJSON,
    RouteOptimizationDepotLoadCostFromJSONTyped,
    RouteOptimizationDepotLoadCostToJSON,
} from './RouteOptimizationDepotLoadCost';

/**
 * Defines the costs for loading and unloading orders at the depot based on load dimensions.
 * @export
 * @interface RouteOptimizationDepotLoadCosts
 */
export interface RouteOptimizationDepotLoadCosts {
    /**
     * A list of costs applied to loads delivered to this depot.
     * @type {Array<RouteOptimizationDepotLoadCost>}
     * @memberof RouteOptimizationDepotLoadCosts
     */
    inbound?: Array<RouteOptimizationDepotLoadCost>;
    /**
     * A list of costs applied to loads picked up at this depot.
     * @type {Array<RouteOptimizationDepotLoadCost>}
     * @memberof RouteOptimizationDepotLoadCosts
     */
    outbound?: Array<RouteOptimizationDepotLoadCost>;
}

/**
 * Check if a given object implements the RouteOptimizationDepotLoadCosts interface.
 */
export function instanceOfRouteOptimizationDepotLoadCosts(value: object): boolean {
    return true;
}

export function RouteOptimizationDepotLoadCostsFromJSON(json: any): RouteOptimizationDepotLoadCosts {
    return RouteOptimizationDepotLoadCostsFromJSONTyped(json, false);
}

export function RouteOptimizationDepotLoadCostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationDepotLoadCosts {
    if (json == null) {
        return json;
    }
    return {
        
        'inbound': json['inbound'] == null ? undefined : ((json['inbound'] as Array<any>).map(RouteOptimizationDepotLoadCostFromJSON)),
        'outbound': json['outbound'] == null ? undefined : ((json['outbound'] as Array<any>).map(RouteOptimizationDepotLoadCostFromJSON)),
    };
}

export function RouteOptimizationDepotLoadCostsToJSON(value?: RouteOptimizationDepotLoadCosts | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'inbound': value['inbound'] == null ? undefined : ((value['inbound'] as Array<any>).map(RouteOptimizationDepotLoadCostToJSON)),
        'outbound': value['outbound'] == null ? undefined : ((value['outbound'] as Array<any>).map(RouteOptimizationDepotLoadCostToJSON)),
    };
}

