/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Restricts how long the driver of the vehicle may work without taking a break of at least the specified duration. All the time spent during a route is considered working time except for waiting time and break time.
 * 
 * @export
 * @interface RouteOptimizationWorkingBreakSettings
 */
export interface RouteOptimizationWorkingBreakSettings {
    /**
     * Describes how long [s] the driver may work without taking a break of at least the specified duration.
     * @type {number}
     * @memberof RouteOptimizationWorkingBreakSettings
     */
    maximumWorkingDuration: number;
    /**
     * Specifies the duration [s] of a break a driver must take if they exceed the maximum working duration.
     * @type {number}
     * @memberof RouteOptimizationWorkingBreakSettings
     */
    minimumBreakDuration: number;
}

/**
 * Check if a given object implements the RouteOptimizationWorkingBreakSettings interface.
 */
export function instanceOfRouteOptimizationWorkingBreakSettings(value: object): boolean {
    if (!('maximumWorkingDuration' in value)) return false;
    if (!('minimumBreakDuration' in value)) return false;
    return true;
}

export function RouteOptimizationWorkingBreakSettingsFromJSON(json: any): RouteOptimizationWorkingBreakSettings {
    return RouteOptimizationWorkingBreakSettingsFromJSONTyped(json, false);
}

export function RouteOptimizationWorkingBreakSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteOptimizationWorkingBreakSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'maximumWorkingDuration': json['maximumWorkingDuration'],
        'minimumBreakDuration': json['minimumBreakDuration'],
    };
}

export function RouteOptimizationWorkingBreakSettingsToJSON(value?: RouteOptimizationWorkingBreakSettings | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'maximumWorkingDuration': value['maximumWorkingDuration'],
        'minimumBreakDuration': value['minimumBreakDuration'],
    };
}

