/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization OptiFlow
 * With the Route Optimization OptiFlow service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Describes the pickup task or the delivery task of an order.
 * @export
 * @interface TaskProperties
 */
export interface TaskProperties {
    /**
     * The unique identifier of the location where the task must be scheduled.
     * @type {string}
     * @memberof TaskProperties
     */
    locationId: string;
    /**
     * A list of unique identifiers of the time slots of the location that can be used to execute this task. When empty all time slots can be used.
     * @type {Array<string>}
     * @memberof TaskProperties
     */
    timeSlotIds?: Array<string>;
    /**
     * The duration [s] it takes to execute this task.
     * @type {number}
     * @memberof TaskProperties
     */
    duration?: number;
    /**
     * A list of categories the task belongs to that can be used to describe constraints.
     * @type {Array<string>}
     * @memberof TaskProperties
     */
    categories?: Array<string>;
}

export function TaskPropertiesFromJSON(json: any): TaskProperties {
    return TaskPropertiesFromJSONTyped(json, false);
}

export function TaskPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locationId': json['locationId'],
        'timeSlotIds': !exists(json, 'timeSlotIds') ? undefined : json['timeSlotIds'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
    };
}

export function TaskPropertiesToJSON(value?: TaskProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locationId': value.locationId,
        'timeSlotIds': value.timeSlotIds,
        'duration': value.duration,
        'categories': value.categories,
    };
}

